export default async function ({ feature, console }) {
  const locationElement = await ScratchTools.waitForElement(
    "p.profile-details > span.location"
  );

  const locationText = locationElement.textContent.trim();
  const countryFlag = getCountryFlag(locationText);
  if (!countryFlag) return;
  const flagElement = document.createElement("span");
  flagElement.textContent = countryFlag;
  flagElement.style.marginRight = "4px";
  feature.self.hideOnDisable(flagElement);
  locationElement.insertBefore(flagElement, locationElement.firstChild);

  function getCountryFlag(locationText) {
    const flags = {
      Afghanistan: "🇦🇫",
      Albania: "🇦🇱",
      Algeria: "🇩🇿",
      "American Somoa": "🇦🇸",
      Andorra: "🇦🇩",
      Angola: "🇦🇴",
      "Antigua and Barbuda": "🇦🇬",
      Argentina: "🇦🇷",
      Armenia: "🇦🇲",
      Australia: "🇦🇺",
      Austria: "🇦🇹",
      Azerbaijan: "🇦🇿",
      "Bahamas, The": "🇧🇸",
      Bahrain: "🇧🇭",
      Bangladesh: "🇧🇩",
      Barbados: "🇧🇧",
      Belarus: "🇧🇾",
      Belgium: "🇧🇪",
      Belize: "🇧🇿",
      Benin: "🇧🇯",
      Bhutan: "🇧🇹",
      Bolivia: "🇧🇴",
      "Bosnia and Herzegovina": "🇧🇦",
      Botswana: "🇧🇼",
      Brazil: "🇧🇷",
      Brunei: "🇧🇳",
      Bulgaria: "🇧🇬",
      "Burkina Faso": "🇧🇫",
      Burma: "🇲🇲",
      Burundi: "🇧🇮",
      "Cabo Verde": "🇨🇻",
      Cambodia: "🇰🇭",
      Cameroon: "🇨🇲",
      Canada: "🇨🇦",
      "Central African Republic": "🇨🇫",
      Chad: "🇹🇩",
      Chile: "🇨🇱",
      China: "🇨🇳",
      Colombia: "🇨🇴",
      Comoros: "🇰🇲",
      "Congo Free State, The": "🇨🇬",
      "Costa Rica": "🇨🇷",
      "Cote d’Ivoire (Ivory Coast)": "🇨🇮",
      Croatia: "🇭🇷",
      Cuba: "🇨🇺",
      Cyprus: "🇨🇾",
      Czechia: "🇨🇿",
      Czechoslovakia: "🇨🇿",
      "Democratic Republic of the Congo": "🇨🇩",
      Denmark: "🇩🇰",
      Djibouti: "🇩🇯",
      Dominica: "🇩🇲",
      "Dominican Republic": "🇩🇴",
      "East Germany (German Democratic Republic)": "🇩🇪",
      Ecuador: "🇪🇨",
      Egypt: "🇪🇬",
      "El Salvador": "🇸🇻",
      "Equatorial Guinea": "🇬🇶",
      Eritrea: "🇪🇷",
      Estonia: "🇪🇪",
      Eswatini: "🇸🇿",
      Ethiopia: "🇪🇹",
      Fiji: "🇫🇯",
      Finland: "🇫🇮",
      France: "🇫🇷",
      Gabon: "🇬🇦",
      "Gambia, The": "🇬🇲",
      Georgia: "🇬🇪",
      Germany: "🇩🇪",
      Ghana: "🇬🇭",
      Greece: "🇬🇷",
      Grenada: "🇬🇩",
      Guatemala: "🇬🇹",
      Guinea: "🇬🇳",
      "Guinea-Bissau": "🇬🇼",
      Guyana: "🇬🇾",
      Haiti: "🇭🇹",
      Hanover: "🇩🇪",
      "Hanseatic Republics": "🇩🇪",
      Hawaii: "🇺🇸",
      Hesse: "🇩🇪",
      "Holy See": "🇻🇦",
      Honduras: "🇭🇳",
      Hungary: "🇭🇺",
      Iceland: "🇮🇸",
      India: "🇮🇳",
      Indonesia: "🇮🇩",
      Iran: "🇮🇷",
      Iraq: "🇮🇶",
      Ireland: "🇮🇪",
      Israel: "🇮🇱",
      Italy: "🇮🇹",
      Jamaica: "🇯🇲",
      Japan: "🇯🇵",
      Jordan: "🇯🇴",
      Kazakhstan: "🇰🇿",
      Kenya: "🇰🇪",
      Serbia: "🇷🇸",
      Kiribati: "🇰🇮",
      Korea: "🇰🇵",
      Kosovo: "🇽🇰",
      Kuwait: "🇰🇼",
      Kyrgyzstan: "🇰🇬",
      Laos: "🇱🇦",
      Latvia: "🇱🇻",
      Lebanon: "🇱🇧",
      Lesotho: "🇱🇸",
      Liberia: "🇱🇷",
      Libya: "🇱🇾",
      Liechtenstein: "🇱🇮",
      Lithuania: "🇱🇹",
      Luxembourg: "🇱🇺",
      Madagascar: "🇲🇬",
      Malawi: "🇲🇼",
      Malaysia: "🇲🇾",
      Maldives: "🇲🇻",
      Mali: "🇲🇱",
      Malta: "🇲🇹",
      "Marshall Islands": "🇲🇭",
      Mauritania: "🇲🇷",
      Mauritius: "🇲🇺",
      Mexico: "🇲🇽",
      Micronesia: "🇫🇲",
      Moldova: "🇲🇩",
      Monaco: "🇲🇨",
      Mongolia: "🇲🇳",
      Montenegro: "🇲🇪",
      Morocco: "🇲🇦",
      Mozambique: "🇲🇿",
      Namibia: "🇳🇦",
      Nauru: "🇳🇷",
      Nepal: "🇳🇵",
      Netherlands: "🇳🇱",
      "New Zealand": "🇳🇿",
      Nicaragua: "🇳🇮",
      Niger: "🇳🇪",
      Nigeria: "🇳🇬",
      "North Macedonia": "🇲🇰",
      "Northern Mariana Islands": "🇲🇵",
      Norway: "🇳🇴",
      Oman: "🇴🇲",
      Pakistan: "🇵🇰",
      Palau: "🇵🇼",
      "Palestine, State of": "🇵🇸",
      Panama: "🇵🇦",
      "Papua New Guinea": "🇵🇬",
      Paraguay: "🇵🇾",
      Peru: "🇵🇪",
      Philippines: "🇵🇭",
      Poland: "🇵🇱",
      Portugal: "🇵🇹",
      Qatar: "🇶🇦",
      Romania: "🇷🇴",
      Russia: "🇷🇺",
      Rwanda: "🇷🇼",
      "Saint Kitts and Nevis": "🇰🇳",
      "Saint Lucia": "🇱🇨",
      "Saint Vincent and the Grenadines": "🇻🇨",
      Samoa: "🇼🇸",
      "San Marino": "🇸🇲",
      "Sao Tome and Principe": "🇸🇹",
      "Saudi Arabia": "🇸🇦",
      Senegal: "🇸🇳",
      Serbia: "🇷🇸",
      Seychelles: "🇸🇨",
      "Sierra Leone": "🇸🇱",
      Singapore: "🇸🇬",
      Slovakia: "🇸🇰",
      Slovenia: "🇸🇮",
      "Solomon Islands": "🇸🇧",
      Somalia: "🇸🇴",
      "South Africa": "🇿🇦",
      "South Sudan": "🇸🇸",
      Spain: "🇪🇸",
      "Sri Lanka": "🇱🇰",
      Sudan: "🇸🇩",
      Suriname: "🇸🇷",
      Sweden: "🇸🇪",
      Switzerland: "🇨🇭",
      Syria: "🇸🇾",
      Taiwan: "🇹🇼",
      Tajikistan: "🇹🇯",
      Tanzania: "🇹🇿",
      Thailand: "🇹🇭",
      "Timor-Leste": "🇹🇱",
      Togo: "🇹🇬",
      Tonga: "🇹🇴",
      "Trinidad and Tobago": "🇹🇹",
      Tunisia: "🇹🇳",
      Turkey: "🇹🇷",
      Turkmenistan: "🇹🇲",
      Tuvalu: "🇹🇻",
      Uganda: "🇺🇬",
      Ukraine: "🇺🇦",
      "United Arab Emirates": "🇦🇪",
      "United Kingdom": "🇬🇧",
      "United States": "🇺🇸",
      Uruguay: "🇺🇾",
      Uzbekistan: "🇺🇿",
      Vanuatu: "🇻🇺",
      Venezuela: "🇻🇪",
      Vietnam: "🇻🇳",
      Yemen: "🇾🇪",
      Zambia: "🇿🇲",
      Zimbabwe: "🇿🇼",
      Antarctica: "🇦🇶",
      "French Southern Territories": "🇹🇫",
      "Bonaire, Sint Eustatius and Saba": " 🇧🇶",
      "Christmas Island": "🇨🇽",
      "Heard Island and McDonald Islands": "🇭🇲",
      "Location not given": "❓",
    };

    return flags[locationText] || "";
  }
}
