export default function () {
  return [
    "Why couldn't the bicycle stand up by itself? It was two-tired.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What did one plate say to the other plate? Dinner's on me!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the math book look sad? Because it had too many problems.",
    "What did one hat say to the other hat? You stay here, I'll go on ahead.",
    "Why don't eggs tell jokes? Because they might crack up!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the cookie go to the doctor? Because it was feeling crumbly.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "What's orange and sounds like a parrot? A carrot!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call a fake noodle? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What did one strawberry say to the other strawberry? If you weren't so sweet, we wouldn't be in this jam!",
    "Why couldn't the leopard play hide and seek? Because he was always spotted!",
    "Why was the broom late? It swept in!",
    "What do you call a bear with no ears? B!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman and a dog? Frostbite!",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "What's brown and sticky? A stick!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did one hat say to the other hat? You stay here, I'll go on ahead!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "What do you call a cow with no legs? Ground beef!",
    "Why don't eggs tell jokes? They might crack up!",
    "Why was the computer cold? It left its Windows open!",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one plate say to the other plate? Dinner's on me!",
    "What's red and smells like blue paint? Red paint!",
    "What do you call a fish with no eyes? Fsh!",
    "Why couldn't the bicycle stand up by itself? It was two-tired!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you get when you cross a snowman and a dog? Frostbite!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "What did one hat say to the other hat? You stay here, I'll go on ahead!",
    "Why was the broom late? It swept in!",
    "What do you call a bear with no ears? B!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman and a dog? Frostbite!",
    "What's brown and sticky? A stick!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What did one hat say to the other hat? You stay here, I'll go on ahead!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "What do you call a cow with no legs? Ground beef!",
    "Why don't eggs tell jokes? They might crack up!",
    "Why was the computer cold? It left its Windows open!",
    "What do you call a sleeping bull? A bulldozer!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one plate say to the other plate? Dinner's on me!",
    "What's red and smells like blue paint? Red paint!",
    "What do you call a fish with no eyes? Fsh!",
    "Why couldn't the bicycle stand up by itself? It was two-tired!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What do you get when you cross a snowman and a dog? Frostbite!",
  ];
}
